### ISSUE TITLE
$nextTick关于microtask优先于 (macro)task执行

### ISSUE THREAD

**Issue by lz-lee** [HcySunYang/vue-design#130]
[nextTick 的实现](http://hcysun.me/vue-design/art/8vue-reactive-dep-watch.html#nexttick-%E7%9A%84%E5%AE%9E%E7%8E%B0)
> 当调用栈空闲后每次事件循环只会从(macro)task 中读取一个任务并执行，而在同一次事件循环内会将 microtask 队列中所有的任务全部执行完毕，且要先于 (macro)task。

执行完一次(macro)task任务之后，会执行所有microtask。microtask优先于第二次(macro)task任务执行是否更合理。

**Comment by miaoyuxinbaby** [comment]
鄙人觉得在原文的基础上修改成如下方式最适合：
当调用栈空闲后每次事件循环会先从(macro)task 中读取一个任务并执行，执行完毕后会将 microtask 队列中的所有任务依次执行，等到microtask 队列清空后再开始下一次事件循环

**Comment by lz-lee** [comment]
原来整体的script代码执行也是macroTask，那么microTask优先于macroTask执行也就说得通了。

**Comment by lbwa** [comment]
根据 [Tasks, microtasks, queues and schedules] 中的介绍 `Microtasks` 中的第二段最后一句话：

> microtasks always happen before the next task.

根据 [W3C] 和 [WHATWG living standard] 所描述的 `event loops processing model` 中，每次 `event loops` 是以一个 `(marco)task` 开始，之后才是 `microtask`。

个人仍然觉得 @lz-lee 所言的 `microtask` 先于 **下一次** (macro)task任务执行更加合理，是否我理解有误？ @HcySunYang 

[Tasks, microtasks, queues and schedules]:https://jakearchibald.com/2015/tasks-microtasks-queues-and-schedules/#why-this-happens

[W3C]:https://www.w3.org/TR/html5/webappapis.html#event-loops

[WHATWG living standard]:https://html.spec.whatwg.org/multipage/webappapis.html#event-loop-processing-model
