### ISSUE TITLE
关于几个package.json的配置属性的作用

### ISSUE THREAD

**Issue by zhaomin94** [HcySunYang/vue-design#153]
您好，最近在拜读您的Vue技术内幕，感觉十分棒！一边跟随您的思路一边对照源码，其中有几个属性很是迷惑。您未曾提及，我也查询了一番，未能找到满意的答案，在这里发起该 Issue 还望指教。这三个属性分别是`pck.unpkg`、`pck.jsdelivr`、`pck.typings`。下面是截图
![image](https://user-images.githubusercontent.com/20993820/44572745-63cc7e80-a7b7-11e8-9ab8-724a09fdc7a9.png)

谢谢您，祝您工作愉快！

**Comment by miaoyuxinbaby** [comment]
@zhaomin94 
这几个是和上传cdn相关的配置，你可以试着google一下，jsdelivr是什么， typings是什么之类的。

另外，vue的文档上也有一点提示 https://cn.vuejs.org/v2/guide/installation.html#CDN
