### ISSUE TITLE
vue-parsing-2 小节中 注释节点的元素描述对象内容这段内容没有实时更新

### ISSUE THREAD

**Issue by MoonYaph** [HcySunYang/vue-design#157]
vue-parsing-2 小节的 注释节点的元素描述对象内容这段内容的错别字还是存在

没人情况 comments 选项的值为 false，即不保留注释，假如将其设置为 true，则当计息期遇到注释节点时会保留该注释节点，此时 parseHTML 函数的 comment 钩子函数会被调用

**Comment by HcySunYang** [comment]
fix
