### ISSUE TITLE
关于$nextTick执行过程中提到的重新渲染

### ISSUE THREAD

**Issue by jadestrong** [HcySunYang/vue-design#158]
在`8vue-reactive-dep-watch.md`文章中有如下一段：
```
callbacks = [
  flushSchedulerQueue, // queue = [renderWatcher]
  () => {
    this.name = 'hcy'
    this.$nextTick(() => { console.log('第二个 $nextTick') })
  }
]
```
>  接下来主线程处于空闲状态(调用栈清空)，开始执行 `microtask` 队列中的任务，即执行 flushCallbacks 函数，`flushCallbacks` 函数会按照顺序执行`callbacks`数组中的函数，首先会执行`flushSchedulerQueue`函数，这个函数会遍历`queue`中的所有观察者并重新求值，完成重新渲染，在完成渲染之后，本次更新队列已经清空，`queue`会被重置为空数组，一切状态还原。接着会执行如下函数：

```
() => {
  this.name = 'hcy'
  this.$nextTick(() => { console.log('第二个 $nextTick') })
}
```
这里提到在`microtask`中的任务flushCallbacks在执行`callbacks`数组，此时数组中有上面的两个函数，而`这个函数会遍历`queue`中的所有观察者并重新求值，完成重新渲染，在完成渲染之后`这句话提到重新渲染，这里的重新渲染是指的浏览器的渲染吗？我在翻查关于`eventloop`的文章时，写的都是浏览器的渲染发生在两个`(macro)task`之间，且是否执行该次渲染根据浏览器的`render`策略决定，具体可查看[深入探究 eventloop 与浏览器渲染的时序问题](https://juejin.im/entry/596d78ee6fb9a06bb752475c)。
所以，我觉的这里的重新渲染应该是指的DOM更新吧，而这里是等`microtask`都执行完后，也就是后面的嵌套的`$nextTick`（应为它也会添加到microtask队列中）也执行完之后，得到最终的DOM，然后会触发浏览器重新渲染，得到渲染后的页面。

以上疑问如果有问题，还请大佬给指正一下，3Q。

**Comment by HcySunYang** [comment]
这里的重新渲染指的是框架层面的 re-render，不是浏览器中的渲染概念，我稍后补充一下
