### ISSUE TITLE
官方文档中的关于extends和mixins的区别解释。

### ISSUE THREAD

**Issue by XingguoHu** [HcySunYang/vue-design#198]
官方文档对于extends的解释：允许声明扩展另一个组件(可以是一个简单的选项对象或构造函数)，而无需使用 Vue.extend。这主要是为了便于扩展单文件组件。这和 mixins 类似，区别在于，组件自身的选项会比要扩展的源组件具有更高的优先级。
不理解 “这和 mixins 类似，区别在于，组件自身的选项会比要扩展的源组件具有更高的优先级。” 这句话。都是通过mergeOptions，mixins和extends为什么会有不一样的优先级。

**Comment by HcySunYang** [comment]
Please read: https://github.com/vuejs/vue/issues/7412
