### ISSUE TITLE
有必要

### ISSUE THREAD

**Issue by aaawhz** [HcySunYang/vue-design#3]
讲这么细吗?

**Comment by aaawhz** [comment]
我写了一个简洁图, 呵呵

**Comment by aaawhz** [comment]
估计你写了至少有30天.

**Comment by aaawhz** [comment]
知道了,你就是写 那篇: 一个真正教会你移动开发;   我看了很久都没搞清楚的   的美团外卖!

后面还是结合其他文章 勉强看懂,  看来文字多了并不能快速 准确把 东西 传递给读者

**Comment by aaawhz** [comment]
不过可以当工具方法了, 有问题直接查..

**Comment by xxxgitone** [comment]
可以好好看一波了👍

**Comment by waihoyu** [comment]
文章中， 有几处附件链接不对，如有必要，博主可以改正一下。

**Comment by HcySunYang** [comment]
@waihoyu 感谢指正，这些问题已经处理，如果后续发现链接不正确的地方希望指出具体一点哦，或直接PR😊

**Comment by aaawhz** [comment]
关注热度很高啊, 昨天我关注的时候, 才4个人, 现在400个了, 估计不出一周, 就能有 4000 个star 了 , 哈哈哈

**Comment by aaawhz** [comment]
建议你再搞个英文版的讲解 ,  超越vue.js 指日可待

**Comment by aaawhz** [comment]
@HcySunYang

**Comment by aaawhz** [comment]
可以当文档查.
