### ISSUE TITLE
Please consider translation to English

### ISSUE THREAD

**Issue by w20k** [HcySunYang/vue-design#41]
Hi,

I'm really looking forward, if it would be possible to have this awesome project translated to Eng!

You did a great job. Awesome project! 
Will manage somehow with google.translate for now ;) Thanks a lot!

Regards,
D.

**Comment by HcySunYang** [comment]
@w20k 
Hi:
Thank you for your compliments. I will seriously consider your suggestions. However, more attention will now be paid to completing these articles, sincerely inviting interested contributors to participate.
