### ISSUE TITLE
关于vue技术内幕中数据响应系统中watch那一部分

### ISSUE THREAD

**Issue by zhangyuang** [HcySunYang/vue-design#56]
![image](https://user-images.githubusercontent.com/17424434/41507295-7b42d26a-7262-11e8-9f5a-adeedf7dc200.png)

这里foreach循环读取data.a.b在这里首先data = data.a 然后data= data.b，先调用了data.a的get方法，此时a属性的dep中push了watch中给a.b属性设置的fn，那这样岂不是会导致当我在set  data.a属性的时候触发watch中给a.b属性设置的fn吗？

**Comment by HcySunYang** [comment]
这里仅仅是一个思路的指引，请看完对于整个源码实现的解析后再来提问，如果任何问题一定虚心改正。感谢您提出的质疑
