### ISSUE TITLE
3vue-example.md中 错误纠正

### ISSUE THREAD

**Issue by waihoyu** [HcySunYang/vue-design#58]
在 3vue-example.md文档中，
..............................................................................................................................
const vm: Component = this
// a uid
vm._uid = uid++
首先声明了变量 vm，其值为 this 也就是当前这个 Vue 实例啦，.........
..............................................................................................................................

vm  应该常量吧？

**Comment by HcySunYang** [comment]
@waihoyu 是的，可以提PR哦😊~
