### ISSUE TITLE
文章中错别字疑问

### ISSUE THREAD

**Issue by waihoyu** [HcySunYang/vue-design#68]
在5vue-merge.md文件中：
1）这个时候则直接返回 mergeDataOrFn 的函数执行结果，但是会多透传一个参数 vm：
疑问：多透传？ “透” 字是多余的吗？
2）那么 mergeHook 函数时怎样合并生命周期选项的呢？我们看看 mergeHook 函数的代码，如下：
疑问：“函数时” ？ 还是 “函数是”
3）整个函数体由三组三目运算符组成，有一点值得大家学习的就是这里写三目运算符的方式，是不是感觉非常的清晰易读？那么这段代码的分析我们同样使用与上面代码相同的格式来写：
疑问：“非常的清晰易读”  应该为 “非常地清晰易读”

**Comment by HcySunYang** [comment]
对于第一个问题，透传的意思是指：在嵌套的函数中，外层函数的参数原封不动的传递给内层函数。
对于另外两个问题：错别字是不可避免的现象，目前有很多热心的读者为这个项目修正错别字并提交pr，在此非常感谢大家的帮助。
