### ISSUE TITLE
Confirm several typos with you

### ISSUE THREAD

**Issue by waihoyu** [HcySunYang/vue-design#86]
Location： 6vue-init-start.md
1.hasHandler 这个变量就定义在当前文件，如下：
const hasHandler = {
    has (target, key) {
        // has 变量是真实经过 in 运算符得来的结果
        const has = key in target
~-----------------------------------------------------
hasHandler 和 has  均为常量.
~-----------------------------------------------------
2.上面的代码由于 render 函数时我们手动书写的，所以 render 函数并不会被包裹在 with 语句块内，
~-----------------------------------------------------
“函数时” or “函数是” ？
~-----------------------------------------------------
3、最后我们注意到 callHook 函数的最后有这段一段代码：
~-----------------------------------------------------
“最后有这段一段代码：” or  “最后有这样一段代码：” ？
~-----------------------------------------------------

**Comment by HcySunYang** [comment]
感谢指正，已修改
