### ISSUE TITLE
关于 Observer 构造函数的理解偏差

### ISSUE THREAD

**Issue by Yawenina** [HcySunYang/vue-design#88]
在 [Observer 构造函数](http://hcysun.me/vue-design/art/7vue-reactive.html#observer-%E6%9E%84%E9%80%A0%E5%87%BD%E6%95%B0) 中写道：

```
export class Observer {
  value: any;
  dep: Dep;
  vmCount: number; // number of vms that has this object as root $data

  constructor (value: any) {
    // 省略...
  }

  walk (obj: Object) {
    // 省略...
  }
  
  observeArray (items: Array<any>) {
    // 省略...
  }
}
```

 > 可以清晰的看到 Observer 类的实例对象将拥有三个实例属性，分别是 value、dep 和 vmCount 以及两个**实例方法** walk 和 observeArray。Observer 类的构造函数接收一个参数，即数据对象。下面我们就从 constructor 方法开始，研究实例化一个 Observer 类时都做了哪些事情。

在`class`中声明的应该是原型方法吧？所以应该是 Observer 类的实例对象拥有 `walk` 和 `observeArray` 两个原型方法吧？

这算是理解上的偏差么？

**Comment by HcySunYang** [comment]
实例方法和原型方法等价，你是不是把实例方法理解为静态方法(类方法)了？

**Comment by Yawenina** [comment]
那应该是我理解有误了。。。谢谢~！
